//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGatewayApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentGatewayApi.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234.
        /// </summary>
        public static string ErrorCode_Validation {
            get {
                return ResourceManager.GetString("ErrorCode_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refer to the status code in the API documentation at http://paymentgateway.com/api/documentation/errors..
        /// </summary>
        public static string ErrorDescription_Generic {
            get {
                return ResourceManager.GetString("ErrorDescription_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refer to the expected input formats in the API documentation at http://paymentgateway.com/api/documentation/errors..
        /// </summary>
        public static string ErrorDescription_Validation {
            get {
                return ResourceManager.GetString("ErrorDescription_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors were found in the request..
        /// </summary>
        public static string ErrorMessage_Validation {
            get {
                return ResourceManager.GetString("ErrorMessage_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CVV must be 3 or 4 digits between 0 and 9..
        /// </summary>
        public static string Validation_CvvRegex {
            get {
                return ResourceManager.GetString("Validation_CvvRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expirationMonth must be between 01 and 12, and the combination of expirationMonth and expirationYear must be a valid date and not be in the past..
        /// </summary>
        public static string Validation_ExpirationMonth {
            get {
                return ResourceManager.GetString("Validation_ExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expirationYear must not be in the past or more than 15 years in the future..
        /// </summary>
        public static string Validation_ExpirationYear {
            get {
                return ResourceManager.GetString("Validation_ExpirationYear", resourceCulture);
            }
        }
    }
}
